### ISSUE TITLE
installation klappt unter contao 3.5.15 nicht

### ISSUE THREAD

**Issue by grashalm4u** [wschwaiger/qwat-tawkto#1]
hallo, wschwaiger,

habe mehrfach versucht, deine erweiterung qwat-tawkto über den internen erweiterungskatalog von contao 3.5.15 zu installieren - vergeblich. die installation selbst klappt noch, aber jeder klick auf einen button wie "weiter" oder "zurück" bringt eine weiße seite hervor. backend und frontend sind anschließend erst wieder erreichbar, wenn ich den tawkto-ordner in den modulen mit ftp komplett lösche, vorher nicht.
habe auch auf der tawkto-seite einen account angelegt und eine url generiert und diese im oberen bereich sämtlicher templates der erweiterung integriert, aber ich kriege sie einfach nicht zum laufen.
was mache ich falsch? oder habe ich was vergessen?
herzlichen dank für eine hilfreiche antwort!

grashalm4u

**Comment by wschwaiger** [comment]
Hallo,

Da stimmt etwas nicht beim Laden der PHP Klassen. Wir gehen dem nach und melden uns mit einem neuen Release wieder.

Danke,
Wolfgang

**Comment by wschwaiger** [comment]
Die neue Version 1.0.1 behebt den Fehler. Ist bereits getestet unter Contao 3.5.15.

vg W

**Comment by grashalm4u** [comment]
hallo, wolfgang!

herzlichen dank für die prompte bearbeitung. werde die neue version gleich mal testen.
sollte ich noch probleme haben, werde ich mich noch mal melden. ansonsten schon mal herzlichen dank auch für die erweiterung an sich.

grashalm4u
