### ISSUE TITLE
anregung zur weiterentwicklung

### ISSUE THREAD

**Issue by grashalm4u** [wschwaiger/qwat-tawkto#2]
hallo wolfgang,

gibt es eine möglichkeit, das chatfenster auf meiner seite irgendwo fest einzubinden (als modul oder content element)? und kann man das jetzt erscheinende chatfenster irgendwo mit css stylen und so dem eigenen layout anpassen? das wäre klasse!
wenn das noch nicht geht, würde ich es mir für die zukunft wünschen.

herzlichen dank,
grashalm4u

**Comment by wschwaiger** [comment]
Hallo,

Danke für die Anregungen.

Add 1) Ist dir die Frontend-Option dafür zu wenig? Was bräuchtest du konkret? Oder willst du es als Modul ins Theme mit aufnehmen?

Add 2) Styling kommt direkt von der Admin-Console von Tawk.to https://www.tawk.to/knowledgebase/chat-widget/customize-the-chat-widget/

W

**Comment by grashalm4u** [comment]
hallo wolfgang,

add 1) >  Ist dir die Frontend-Option dafür zu wenig?

ehrlich gesagt: ja! optimal wäre es, wenn ich es bei den modulen auswählen und ins theme integrieren könnte. dann nämlich an die stelle, wo ich es hin haben möchte. im moment hängt es bei mir ein wenig "lustlos" am linken unteren ende des monitors herum (s.: [www.die-schreibmaus.de](url)).

add 2) danke für den styling-hinweis. habe es jetzt - soweit möglich - ein wenig angepasst.

liebe grüße,

grashalm4u

**Comment by wschwaiger** [comment]
hi,

die integration des codes hält sich an die anleitung von tawk.to, den code direkt vor dem `</body>` zu integrieren, https://www.tawk.to/knowledgebase/getting-started/adding-a-widget-to-your-website/. die position scheint also zu passen auf www.die-schreibmaus.de

ich sehe leider keinen sinn es wo anders unter zu bringen. page lock etc. lieber ganz am schluss laden, sonst lädt unter umständen nichts mehr.

W
